from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

from urllib.request import urlopen
from urllib.error import URLError

try:
    response = urlopen('https://www.google.com/', timeout=10)
    iconnect = True
except urllib.error.URLError as ex:
    iconnect = False


class dummyprovider:
    def remote(string_, allow_redirects="foo", immediate_close="bar"):
        return string_

if iconnect: # and not ('nointernet' in config and config['nointernet']):
    FTP = FTPRemoteProvider()
    HTTP = HTTPRemoteProvider()
else:
    FTP = dummyprovider
    HTTP = dummyprovider


BioMe_dir = "/sc/arion/projects/LOAD/Data/BioME/sample_QC/GWASampleFiltering/input/"

DATASETS_all = ["BioMe_array-regeneron_GSA", "BioMe_array-sema4_GDA", "NYSCF_array"]
DATASETS = ["BioMe_array-regeneron_GSA", "BioMe_array-sema4_GDA"]
CHROMS = 17
BUILD = "hg19"
array = True

rule all:
    input:
        "output/merged.vcf.gz"
        #expand('output/{dataset}_chr{chrom}/{dataset}_chr{chrom}.vcf.gz',
        #       dataset=DATASETS, chrom=CHROMS)

rule biome_filter:
    input: multiext(BioMe_dir + "{bmcenter}_hg19", ".bed", ".bim", ".fam")
    output: multiext("intermediate/BioMe_array-{bmcenter}", ".bed", ".bim", ".fam")
    params:
        ins = BioMe_dir + "{bmcenter}_hg19",
        out = "intermediate/BioMe_array-{bmcenter}"
    resources:
        mem_mb = 10000,
        time_min = 30
    conda: "envs/plink.yaml"
    shell:
        """
plink --bfile {params.ins} --chr 17 --make-bed --out {params.out}
"""

rule NYCSF_binary:
    input: multiext("input/NYSCF_MSSM_Chr17", ".ped", ".map")
    output: multiext("intermediate/NYSCF_array", ".bed", ".bim", ".fam")
    params:
        ins = "input/NYSCF_MSSM_Chr17",
        out = "intermediate/NYSCF_array"
    resources:
        mem_mb = 10000,
        time_min = 30
    conda: "envs/plink.yaml"
    shell:
        """
plink --file {params.ins} --make-bed --out {params.out}
"""

rule Sample_Flip:
    input:
        bim = "intermediate/{dataset}" + '.bim',
        bed = "intermediate/{dataset}" + '.bed',
        fam = "intermediate/{dataset}" + '.fam',
        fasta = expand("reference/human_g1k_{gbuild}.fasta", gbuild=BUILD)
    output:
        multiext("intermediate/{dataset}_flipped", ".bim", ".bed", ".fam")
    params:
        stem = "intermediate/{dataset}"
    resources:
        mem_mb = 10000,
        time_min = 30
    container: 'docker://befh/flippyr:0.5.3'
    shell: "flippyr -p {input.fasta} -o {params.stem} {input.bim}"

rule Sample_ChromPosRefAlt:
    input:
        flipped = "intermediate/{dataset}_flipped.bim"
    output:
        bim = temp("intermediate/{dataset}_flipped_ChromPos.bim"),
        snplist = temp("intermediate/{dataset}_flipped_snplist")
    threads: 2
    resources:
        mem_mb = 8000,
        time_min = 30
    container: 'docker://befh/r_env_gwasamplefilt:5'
    script: 'scripts/bim_ChromPosRefAlt.R'

# Recode sample plink file to vcf
rule vcf:
    input:
        bed = "intermediate/{dataset}_flipped.bed",
        bim = "intermediate/{dataset}_flipped_ChromPos.bim",
        fam = "intermediate/{dataset}_flipped.fam"
    output: "intermediate/{dataset}.vcf.gz"
    params:
        out = "intermediate/{dataset}"
    resources:
        mem_mb = 10000,
        time_min = 30
    conda: "envs/plink.yaml"
    shell:
        '''
plink --bed {input.bed} --bim {input.bim} --fam {input.fam} --recode vcf bgz \
  --real-ref-alleles --out {params.out}
'''


rule idx_vcf:
    input: "intermediate/{dataset}.vcf.gz"
    output: "intermediate/{dataset}.vcf.gz.tbi"
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 30
    shell: "bcftools index -t {input}"

rule bcf:
    input:
        vcf = "intermediate/{dataset}.vcf.gz",
        tbi = "intermediate/{dataset}.vcf.gz.tbi",
        fasta = "reference/human_g1k_{build}.fasta"
    output: "intermediate/{dataset}_chr{chrom}.{build}.bcf"
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 30
    shell:
        """
bcftools view -r {wildcards.chrom} {input.vcf} | \
  bcftools norm -Ob -o {output} -d none -f {input.fasta} && \
bcftools index {output}
"""

rule makeref_tg:
    input:
        vcf = "reference/1000gRaw.{build}.chr{chrom}.vcf.gz",
        fasta = "reference/human_g1k_{build}.fasta"
    output: "reference_proc/1000g.{build}.chr{chrom}.bcf"
    conda: "envs/bcftools.yaml"
    threads: 4
    resources:
        mem_mb = 4000,
        time_min = 30
    shell:
        '''
bcftools view -Ou -c 2 {input.vcf} | \
  bcftools norm -Ou -m -any | \
  bcftools norm -Ob -o {output} -d none -f {input.fasta} && \
 bcftools index -f {output}
'''

rule filter_ref:
    input:
      ref = rules.makeref_tg.output,
      samp = rules.vcf.output
    output: "reference_proc/1000g.{build}.chr{chrom}.filtered_{dataset}.vcf.gz"
    conda: "envs/bcftools.yaml"
    threads: 4
    resources:
        mem_mb = 4000,
        time_min = 30
    shell:
        '''
bcftools view --regions-file {input.samp} -Oz -o {output} {input.ref}
bcftools index -f {output}
'''

rule eagle:
    input:
        target = expand("intermediate/{{dataset}}_chr{{chrom}}.{build}.bcf", build=BUILD),
        ref = expand("reference_proc/1000g.{build}.chr{{chrom}}.bcf", build=BUILD)
    output: "intermediate/{dataset}_chr{chrom}_phased.vcf.gz"
    params:
        outstem = "intermediate/{dataset}_chr{chrom}_phased"
    log: "logs/{dataset}_chr{chrom}.eagle.log"
    threads: 10
    resources:
        mem_mb = 4000,
        walltime = '4:00'
    container: 'docker://befh/eagle:v2.4.1'
    shell:
        '''
eagle --vcfTarget={input.target} --vcfRef={input.ref} \
  --geneticMapFile=/tables/genetic_map_hg19_withX.txt.gz \
  --outPrefix={params.outstem} --numThreads=10 --vcfOutFormat=z \
  2>&1 | tee {log}
'''

rule geneticMapGnomix:
    input: HTTP.remote("https://storage.googleapis.com/broad-alkesgroup-public/Eagle/downloads/tables/genetic_map_hg19_withX.txt.gz") if iconnect else ''
    output: "reference_proc/genetic_map_hg19_withX.gmap"
    resources:
        mem_mb = 1000,
        time_min = 30
    shell:
        r'''
zcat {input} | \
  awk 'BEGIN {{OFS="\t"; print "#chromosome\tposition\tGenetic_Map(cM)"}} NR > 1 {{print $1,$2,$4}}' \
  > {output}
'''

reporoot = "https://raw.githubusercontent.com/AI-sandbox/gnomix/main" 
confstem = "https://raw.githubusercontent.com/AI-sandbox/gnomix/main/configs"
if array:
    gconfig = HTTP.remote(reporoot + "/configs/config_array.yaml") if iconnect else ''
else:
    gconfig = HTTP.remote(reporoot + "/configs/config.yaml") if iconnect else ''

rule sample_list:
    input: expand("intermediate/{{dataset}}_chr{chrom}_phased.vcf.gz", chrom=CHROMS)
    output: "intermediate/sample_lists/{dataset}_all.txt",
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 30
    shell: "bcftools query -l {input[0]} > {output}"

checkpoint sample_list_split:
    input: rules.sample_list.output
    output: directory("intermediate/sample_lists/split_{dataset}")
    params:
        splitstem = "intermediate/sample_lists/split_{dataset}/split."
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 30
    shell: "mkdir -p {output} && split -l 100 -a 4 -d {input} {params.splitstem}"

rule splits:
    input:
        sample_list = "intermediate/sample_lists/split_{dataset}/split.{chunk}",
        vcf = rules.eagle.output
    output:
        vcf = temp("intermediate/{dataset}_chr{chrom}_phased.{chunk}.vcf.gz"),
        tbi = temp("intermediate/{dataset}_chr{chrom}_phased.{chunk}.vcf.gz.tbi"),
    conda: "envs/bcftools.yaml"
    threads: 4
    resources:
        mem_mb = 4000,
        time_min = 30
    shell:
        '''
bcftools view --samples-file {input.sample_list} -Oz -o {output.vcf} {input.vcf}
bcftools index -tf {output.vcf}
'''

rule vcf_model_fit:
    input:
        sample_list = rules.sample_list.output,
        vcf = rules.eagle.output
    output:
        sample_list = temp("intermediate/{dataset}_chr{chrom}_phased_modelfit.samples"),
        vcf = temp("intermediate/{dataset}_chr{chrom}_phased_modelfit.vcf.gz"),
        tbi = temp("intermediate/{dataset}_chr{chrom}_phased_modelfit.vcf.gz.tbi"),
    conda: "envs/bcftools.yaml"
    threads: 4
    resources:
        mem_mb = 4000,
        time_min = 30
    shell:
        '''
head -n4 {input.sample_list} > {output.sample_list}
bcftools view --samples-file {output.sample_list} -Oz -o {output.vcf} {input.vcf}
bcftools index -tf {output.vcf}
'''

rule gnomix_model:
    input:
        query = "intermediate/{dataset}_chr{chrom}_phased_modelfit.vcf.gz",
        genetic_map = rules.geneticMapGnomix.output,
        reference = expand("reference_proc/1000g.{build}.chr{{chrom}}.filtered_{{dataset}}.vcf.gz", build=BUILD),
        sample_map = HTTP.remote(reporoot + "/demo/data/1000g.smap") if iconnect else '',
        config = gconfig
    output:
        'output/models/{dataset}_chr{chrom}/models/model_chm_{chrom}/model_chm_{chrom}.pkl'
    params:
        output_folder = 'output/models/{dataset}_chr{chrom}',
        phase = 'False', #True or False
    threads: 40
    resources:
        mem_mb = 4000,
        walltime = '140:00'
    container: "docker://befh/gnomix:v2"
    shell:
        '''
python3 /gnomix/gnomix.py {input.query} {params.output_folder} \
  {wildcards.chrom} {params.phase} \
  {input.genetic_map} {input.reference} {input.sample_map} \
  {input.config}
'''

gchunkdir = 'output/chunked/{dataset}_chr{chrom}_chunk{chunk}'

rule gnomix:
    input:
        query = "intermediate/{dataset}_chr{chrom}_phased.{chunk}.vcf.gz",
        model = rules.gnomix_model.output
    output:
        vcf = temp(gchunkdir + '/query_file_phased.vcf'),
        fb = gchunkdir + '/query_results.fb',
        msp = gchunkdir + '/query_results.msp'
    params:
        output_folder = gchunkdir,
        phase = 'True', #True or False
    threads: 40
    resources:
        mem_mb = 2000,
        walltime = '140:00'
    container: "docker://befh/gnomix:v2"
    shell:
        '''
python3 /gnomix/gnomix.py {input.query} {params.output_folder} \
  {wildcards.chrom} {params.phase} {input.model}
'''

rule Compress:
    input: gchunkdir + '/query_file_phased.vcf'
    output:
        vcf = gchunkdir + '/{dataset}_chr{chrom}.vcf.gz',
        tbi = gchunkdir + '/{dataset}_chr{chrom}.vcf.gz.tbi'
    threads: 2
    resources:
        mem_mb = 4000,
        walltime = '4:00'
    conda: "envs/bcftools.yaml"
    shell:
        '''
bcftools view -Oz -o {output.vcf} {input}
bcftools index -tf {output.vcf}
'''

gchunkdirp = 'output/chunked/{{dataset}}_chr{{chrom}}_chunk{chunk}'

def aggregate(wildcards, fname):
    #import ipdb; ipdb.set_trace()
    checkpoint_output = checkpoints.sample_list_split.get(**wildcards).output[0]
    chunks = glob_wildcards(checkpoint_output + "/split.{chunk}").chunk
    # ins = {
    #     "vcf": expand(gchunkdir + '/{{dataset}}_chr{{chrom}}.vcf.gz', chunk=chunks),
    #     "fb": expand(gchunkdir + '/query_results.fb', chunk=chunks),
    #     "msp": expand(gchunkdir + '/query_results.msp', chunk=chunks)
    # }
    # return ins
    return expand(gchunkdirp + fname, chunk=chunks)

rule merge_gnomad:
    input:
        vcf = lambda wc: aggregate(wc, '/{{dataset}}_chr{{chrom}}.vcf.gz'),
        tbi = lambda wc: aggregate(wc, '/{{dataset}}_chr{{chrom}}.vcf.gz.tbi'), 
        fb = lambda wc: aggregate(wc, '/query_results.fb'), 
        msp = lambda wc: aggregate(wc, '/query_results.msp') 
    output:
        vcf = 'output/merged/{dataset}_chr{chrom}.vcf.gz',
        tbi = 'output/merged/{dataset}_chr{chrom}.vcf.gz.tbi',
        msp = 'output/merged/{dataset}_chr{chrom}.msp',
        fb = 'output/merged/{dataset}_chr{chrom}.fb',
        tmp = temp('output/merged/{dataset}_chr{chrom}.tmp')
    threads: 2
    resources:
        mem_mb = 4000,
        walltime = '4:00'
    conda: "envs/gnomad_merge.yaml"
    shell:
        r'''
bcftools merge -Oz -o {output.vcf} {input.vcf}
bcftools index -tf {output.vcf}

tmpfile={output.tmp}
out_msp={output.msp}
out_fb={output.fb}

msps=({input.msp}) # make array of inputs
msp_first="${{msps[0]}}"
cp "$msp_first" "$out_msp" # copy first input to output
msps=("${{msps[@]:1}}") # delete first input from array

for msp in ${{msps[@]}}; do
  if ! diff -q <(cut -f1-6 "$msp_first") <(cut -f1-6 "$msp"); then
    echo "$msp has different variant ranges than the first chunk"
    exit 1
  fi
  paste "$out_msp" <(cut -f1-6 --complement $msp) > "$tmpfile"
  cp "$tmpfile" "$out_msp"
  nrow=$(cat "$out_msp" | tail -n +3 | wc -l)
  ncol=$(sed -n '2{{s/\t/\n/g;p;q}}' "$out_msp" | tail -n +7 | wc -l)
  echo $msp "$nrow" rows, "$ncol" columns
done

rm "$tmpfile"

fbs=({input.fb}) # make array of inputs
fb_first="${{fbs[0]}}"
cp "$fb_first" "$out_fb" # copy first input to output
fbs=("${{fbs[@]:1}}") # delete first input from array

for fb in ${{fbs[@]}}; do
  if ! diff -q <(cut -f1-4 "$fb_first") <(cut -f1-4 "$fb"); then
    echo "$msp has different variant ranges than the first chunk"
    #exit 1
  fi
  paste $out_fb <(cut -f1-4 --complement $fb) > "$tmpfile"
  cp "$tmpfile" "$out_fb"
  nrow=$(cat "$out_fb" | tail -n +3 | wc -l)
  ncol=$(sed -n '2{{s/\t/\n/g;p;q}}' "$out_fb" | tail -n +5 | wc -l)
  echo $fb: "$nrow" rows, "$ncol" columns
done

get_head () {{
  awk 'NR == 1 {{a[$0]; print; next}} FNR == 1 && !($0 in a) \
    {{print "Header comment different"; exit 1}}' $@
}}

replace_head () {{ sed -i "1 s|^.*$|$1|" $2 ; }}

header_fb="$(get_head {input.fb})"
header_msp="$(get_head {input.msp})"

replace_head "$header_fb" "$out_fb"
replace_head "$header_msp" "$out_msp"
'''

rule Concatenate:
    input:
        vcf = expand('output/merged/{{dataset}}_chr{chrom}.vcf.gz', chrom=CHROMS),
        tbi = expand('output/merged/{{dataset}}_chr{chrom}.vcf.gz.tbi', chrom=CHROMS),
    output:
        vcf = 'output/{dataset}_chrall.vcf.gz',
        tbi = 'output/{dataset}_chrall.vcf.gz.tbi'
    threads: 4
    resources:
        mem_mb = 4000,
        walltime = '4:00'
    conda: "envs/bcftools.yaml"
    shell:
        r'''
bcftools concat -Oz -o {output.vcf} --threads 2 {input.vcf}
bcftools index -tf {output.vcf}
'''

rule Merge:
    input:
        vcf = expand('output/{dataset}_chrall.vcf.gz', dataset=DATASETS),
        tbi = expand('output/{dataset}_chrall.vcf.gz.tbi', dataset=DATASETS)
    output:
        vcf = "output/merged.vcf.gz",
        tbi = "output/merged.vcf.gz.tbi"
    threads: 4
    resources:
        mem_mb = 4000,
        walltime = '4:00'
    conda: "envs/bcftools.yaml"
    shell:
        r'''
bcftools merge -m none -Oz -o {output.vcf} --threads 2 {input.vcf}
bcftools index -tf {output.vcf}
'''
