from snakemake.utils import min_version
min_version("7.0")

# ruleorder: vcf_presplit > splits > merge_gnomix > Concatenate > Compress > imputation_sort_vcf_allchr > shapeit_index_vcf

import re
from snakemake.remote.FTP import RemoteProvider as FTPRemoteProvider
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

from urllib.request import urlopen
from urllib.error import URLError

try:
    response = urlopen('https://www.google.com/', timeout=10)
    iconnect = True
except URLError as ex:
    iconnect = False


configfile: "config/config.yaml"

class dummyprovider:
    def remote(string_, allow_redirects="foo", immediate_close="bar"):
        return string_

if iconnect: # and not ('nointernet' in config and config['nointernet']):
    FTP = FTPRemoteProvider()
    HTTP = HTTPRemoteProvider()
else:
    FTP = dummyprovider
    HTTP = dummyprovider

#import ipdb; ipdb.set_trace()

reporoot = "raw.githubusercontent.com/AI-sandbox/gnomix/main" 

ref_vcf = {"hg19": "reference/1000gRaw.hg19.chr{chrom}.vcf.gz",
           "hg38": "/sc/arion/projects/sharpa01a/1000Genomes_HGDP_Phased_VCFs/hgdp.tgp.gwaspy.merged.chr{chrom}.merged.cleaned.vcf.gz"} # "reference/1000gRaw.GRCh38.chr{chrom}.vcf.gz"}
ref_fasta = {"hg19": "reference/human_g1k_hg19.fasta",
             "hg38": "reference/human_gatk_GRCh38.fasta"}
ref_pops = {"hg19": HTTP.remote(reporoot + "/demo/data/1000g.smap") if iconnect else '',
            "hg38": 'reference_proc/hgdp_1kg_filt.smap'}
ref_name = {"hg19": "1000g", "hg38": "hgdp_1kg"}

tgbase = "http://ftp-trace.ncbi.nih.gov/1000genomes/ftp/"
tgbase_38 = ("https://storage.googleapis.com/" +
             "gcp-public-data--broad-references/hg38/v0/")

tgfasta = dict(
    hg19=(tgbase + "technical/reference/human_g1k_v37.fasta.gz"),
    GRCh38=(tgbase_38 + 'Homo_sapiens_assembly38.fasta'))

def fasta_remote(wc):
    gbuild = wc.gbuild
    return HTTP.remote(tgfasta[gbuild])
    # if gbuild == 'GRCh38':
    #     return FTP.remote(tgfasta['GRCh38'], immediate_close=True)
    # else:
    #     return HTTP.remote(tgfasta[gbuild])

def fasta_md5(wc):
    gbuild = wc.gbuild
    if gbuild == 'GRCh38':
        return '7ff134953dcca8c8997453bbb80b6b5e'
    elif gbuild == 'hg19':
        return '45f81df94f0408d082363e34a081ed81'

conf = config['datasets']

def get_build(conf, dataset):
    if conf[dataset].get('impute', False):
        return 'hg38'
    else:
        return conf[dataset]['build']

def get_intype(conf, dataset):
    fname = conf[dataset]['infile']
    if re.match(r'.+\.vcf(\.b{0,1}gz)*$', fname):
        return 'vcf'
    elif re.match(r'.+\.bcf$', fname):
        return 'bcf'
    elif re.match(r'.+\.bed$', fname):
        return 'bplink'
    elif re.match(r'.+\.ped$', fname):
        return 'plink'
    else:
        raise Exception('Unrecognized file type')

def get_in(conf, dataset):
    fname = conf[dataset]['infile']
    fname = fname.format(indir=config['indir'], chrom='{chrom}') #allow
    intype = get_intype(conf, dataset)
    if intype in ['plink', 'bplink']:
        return fname[0:-4]
    else:
        return fname

def parse_chrom(chrs):
    clist = [x.split(":") for x in chrs.split(",")]
    parsed = []
    for chrs in clist:
        if len(chrs) == 2:
            chrs = [str(c) for c in range(int(chrs[0]), int(chrs[1]) + 1)]
        elif len(chrs) != 1:
            raise ValueError("Invalid chromosome list.")
        parsed += chrs
    return parsed


if 'chroms' not in config:
    CHROMS = parse_chrom('1:22')
else:
    CHROMS = parse_chrom(config['chroms'])

DATASETS = [x for x in conf.keys()]
BUILD = [get_build(conf, x) for x in DATASETS] # hg19 or hg38
array = [conf[x]['array'] for x in DATASETS]
filter_dict = {x: conf[x].get('filters', '') for x in DATASETS}
input_type_dict = {x: get_intype(conf, x) for x in DATASETS}
input_dict = {x: get_in(conf, x) for x in DATASETS}
impute_datasets = [x for x in DATASETS if conf[x].get('impute', False)]
impute_build = [conf[x]['build'] for x in DATASETS if conf[x].get('impute', False)]
if len(impute_build) > 0:
    assert len(set(impute_build)) == 1, "There can only be one build for imputation"
    impute_build = impute_build[0]
    assert impute_build in ['hg19', 'hg38']
else:
    impute_build = 'hg19'
impute_fasta = ref_fasta[impute_build]

gconfig_filename_dict = {
  k: ("config_array.yaml" if v else "config.yaml") for k, v in zip(DATASETS, array)}
gconfig_local_dict = {
  k: f'intermediate/configs/{v}' for k, v in gconfig_filename_dict.items()}

def dict_settings(setting):
    return {k: v for k, v in zip(DATASETS, setting)}

build_dict = dict_settings(BUILD)

wildcard_constraints:
    build='hg(19|38)'

rule all:
    input:
        "output/merged.vcf.gz"
        #expand('output/{dataset}_chr{chrom}/{dataset}_chr{chrom}.vcf.gz',
        #       dataset=DATASETS, chrom=CHROMS)

rule download_tg_fa:
    input: fasta_remote
    output:
        "reference/human_{source}_{gbuild}.fasta",
        "reference/human_{source}_{gbuild}.fasta.fai"
    params:
        md5 = lambda wc: fasta_md5(wc)
    resources:
        mem_mb = 10000,
        time_min = 30
    conda: 'envs/bcftools.yaml'
    localrule: True
    #cache: True
    shell:
        '''
md5sum -c <(echo {params.md5} {input[0]})
if [[ "{input[0]}" == *.gz ]]; then
  zcat {input[0]} > {output[0]} && rstatus=0 || rstatus=$?; true
  if [ $rstatus -ne 2 && $rstatus -ne 0 ]; then
    exit $rstatus
  fi
else
  cp {input[0]} {output[0]}
fi
samtools faidx {output[0]}
'''

def get_intype(wc):
    intype_ =  wc['inputtype']
    if intype_ == 'bplink':
        return 'bfile'
    elif intype_ == 'plink':
        return 'file'
    else:
        raise Exception('Invalid input type')

def get_infile(wc):
    intype_ = wc['inputtype']
    stem = input_dict[wc['dataset']]
    if intype_ == 'bplink':
        return multiext(stem, ".bed", ".bim", ".fam")
    elif intype_ == 'plink':
        return multiext(stem, ".ped", ".map")
    else:
        raise Exception('Invalid input type')

rule plink_filter:
    input: get_infile
    output: temp(multiext("intermediate/start/{dataset}.{build}.from{inputtype}", ".bed", ".bim", ".fam"))
    params:
        ins = lambda wc: input_dict[wc['dataset']],
        out = "intermediate/start/{dataset}.{build}.from{inputtype}",
        filt = lambda wc: filter_dict[wc['dataset']],
        ftype = get_intype
    resources:
        mem_mb = 10000,
        time_min = 30
    conda: "envs/plink.yaml"
    shell:
        """
plink --{params.ftype} {params.ins} {params.filt} --make-bed --out {params.out}
"""

def preimpute_files(wc):
    ds = wc['dataset']
    intype = input_type_dict[ds]
    stem = expand("intermediate/start/{dataset}.{build}.from{inputtype}",
        inputtype=intype, build=impute_build, dataset=ds)[0]
    return {x: stem + '.' + x for x in ['bed', 'bim', 'fam']}

rule link_impute:
    input: unpack(preimpute_files)
    output:
        bed = "intermediate/impute_start/{dataset}.bed",
        bim = "intermediate/impute_start/{dataset}.bim",
        fam = "intermediate/impute_start/{dataset}.fam"
    resources:
        mem_mb = 1000,
        time_min = 30
    shell:
        '''
cp {input.bed} {output.bed}
cp {input.bim} {output.bim}
cp {input.fam} {output.fam}
'''
    

config_impute = config["imputation"]
config_impute["chroms"] = config["chroms"]
config_impute["directory"] = "intermediate/impute_start/"
config_impute["SAMPLES"] = impute_datasets
config_impute["out_dir"] = "output/imputation"
config_impute['ref'] = impute_fasta
config_impute['imputation']['default']['build'] = impute_build
config_impute['imputation']['default']['refpanel'] = 'topmed-r3'

if 'pipeline_versions' not in config:
    config['pipeline_versions'] = {}
if 'imputePipeline' not in config['pipeline_versions']:
    config['pipeline_versions']['imputePipeline'] = 'v0.4.10'
if 'shapeit5_pipeline' not in config['pipeline_versions']:
    config['pipeline_versions']['shapeit5_pipeline'] = '866c2e3'
version_impute = config['pipeline_versions']['imputePipeline']
version_shapeit = config['pipeline_versions']['shapeit5_pipeline']

if 'postImpute' in config['pipeline_versions']:
    config_impute['version_postImpute'] = config['pipeline_versions']['postImpute']

if re.match(r'/', version_impute):
    snakefile_impute = os.path.join(
        os.path.normpath(version_impute), 'workflow', 'Snakefile')
else:
    snakefile_impute = github("marcoralab/imputePipeline",
        path="workflow/Snakefile", tag=version_impute)

if re.match(r'/', version_shapeit):
    snakefile_shapeit = os.path.join(
        os.path.normpath(version_shapeit), 'workflow', 'Snakefile')
else:
    snakefile_shapeit = github("marcoralab/shapeit5_pipeline",
        path="workflow/Snakefile", tag=version_shapeit)

module imputation:
    snakefile: snakefile_impute
    config: config_impute

use rule * from imputation as imputation_*

rule Sample_Flip:
    input:
        bim = "intermediate/start/{dataset}.{build}.from{inputtype}" + '.bim',
        bed = "intermediate/start/{dataset}.{build}.from{inputtype}" + '.bed',
        fam = "intermediate/start/{dataset}.{build}.from{inputtype}" + '.fam',
        fasta = lambda wc: ref_fasta[wc["build"]]
    output:
        temp(multiext("intermediate/{dataset}.{build}.from{inputtype}_flipped", ".bim", ".bed", ".fam"))
    params:
        stem = "intermediate/{dataset}.{build}.from{inputtype}"
    resources:
        mem_mb = 10000,
        time_min = 30
    container: 'docker://befh/flippyr:0.5.3'
    shell: "flippyr -p {input.fasta} -o {params.stem} {input.bim}"

rule Sample_ChromPosRefAlt:
    input:
        flipped = "intermediate/{dataset}.{build}.from{inputtype}_flipped.bim"
    output:
        bim = temp("intermediate/{dataset}.{build}.from{inputtype}_flipped_ChromPos.bim"),
        snplist = temp("intermediate/{dataset}.{build}.from{inputtype}_flipped_snplist")
    threads: 2
    resources:
        mem_mb = 8000,
        time_min = 30
    container: 'docker://befh/r_env_gwasamplefilt:5'
    script: 'scripts/bim_ChromPosRefAlt.R'

rule rename_chrom:
    input:
        fasta = lambda wc: ref_fasta[wc["build"]],
    output:
        json = 'intermediate/rename/{dataset}.{build}.from{inputtype}_mapping.json',
        mapping = 'intermediate/rename/{dataset}.{build}.from{inputtype}_mapping.txt'
    threads: 1
    resources:
        mem_mb = 256,
        time_min = 10
    container: 'docker://befh/flippyr:0.5.3'
    script: 'scripts/rule_rename_chrom.py'

# Recode sample plink file to vcf
rule plink_vcf:
    input:
        bed = "intermediate/{dataset}.{build}.from{inputtype}_flipped.bed",
        bim = "intermediate/{dataset}.{build}.from{inputtype}_flipped_ChromPos.bim",
        fam = "intermediate/{dataset}.{build}.from{inputtype}_flipped.fam"
    output: temp("intermediate/{dataset}.{build}.from{inputtype}.plink_contigs.vcf.gz")
    params:
        out = "intermediate/{dataset}.{build}.from{inputtype}.plink_contigs"
    threads: 40
    resources:
        mem_mb = 4000,
        time_min = 1440
    conda: "envs/plink2.yaml"
    shell:
        '''
plink2 --bed {input.bed} --bim {input.bim} --fam {input.fam} --recode vcf bgz \
  --real-ref-alleles --out {params.out} --threads {threads} --memory 160000
'''

rule rename_vcf:
    input:
        vcf = rules.plink_vcf.output,
        mapping = rules.rename_chrom.output.mapping
    output: temp("intermediate/{dataset}.{build}.from{inputtype}.vcf.gz")
    threads: 4
    resources:
        mem_mb = 2048,
        time_min = 2880
    conda: "envs/bcftools.yaml"
    shell:
        '''
bcftools annotate --rename-chrs {input.mapping} -Oz -o {output} --threads {threads} {input.vcf}
'''

def choose_vcf_initial(wc):
    ds = wc['dataset']
    intype = input_type_dict[ds]
    if conf[ds].get('impute', False):
        raise Exception("Phasing not needed after imputation")
    # elif conf[ds].get('phased', False):
    #     raise Exception("Phasing not needed")
    elif intype == 'bcf':
        raise Exception("BCF not yet supported")
    elif intype == 'vcf':
        return conf[ds]['infile']
    else:
        return expand("intermediate/{{dataset}}.{{build}}.from{inputtype}.vcf.gz",
            inputtype = intype)

def choose_filter_vcf_initial(wc):
    ds = wc['dataset']
    intype = input_type_dict[ds]
    if conf[ds].get('impute', False):
        raise Exception("Phasing not needed after imputation")
    # elif conf[ds].get('phased', False):
    #     raise Exception("Phasing not needed")
    elif intype == 'bcf':
        raise Exception("BCF not yet supported")
    elif intype == 'vcf':
        return filter_dict[ds]
    else:
        return ''

rule vcf:
    input: choose_vcf_initial
    output:
        vcf = temp("intermediate/{dataset}.{build}.allchrom.vcf.gz"),
        tbi = "intermediate/{dataset}.{build}.allchrom.vcf.gz.tbi"
    params:
        filt = choose_filter_vcf_initial
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 8600
    shell: '''
filt="{params.filt}"
if [[ -z "${{filt// }}" ]]; then
  cp {input} {output.vcf}
else
  bcftools view {params.filt} -Oz -o {output.vcf} {input}
fi
bcftools index -t {output.vcf}
'''

rule vcf_split:
    input:
        vcf = rules.vcf.output.vcf,
        tbi = rules.vcf.output.tbi
    output:
        vcf = temp("intermediate/{dataset}.{build}.chr{chrom}.pipesplit.vcf.gz"),
        tbi = "intermediate/{dataset}.{build}.chr{chrom}.pipesplit.vcf.gz.tbi"
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 16000,
        time_min = 8600
    shell: '''
bcftools view -r {wildcards.chrom} -Oz -o {output.vcf} {input.vcf} && \
sleep 5 && \
bcftools index -t {output.vcf}
'''

rule vcf_presplit:
    input: choose_vcf_initial
    output:
        vcf = temp("intermediate/{dataset}.{build}.chr{chrom}.perchrom.vcf.gz"),
        tbi = "intermediate/{dataset}.{build}.chr{chrom}.perchrom.vcf.gz.tbi"
    params:
        filt = lambda wc: filter_dict[wc['dataset']],
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 8600
    shell: '''
filt="{params.filt}"
if [[ -z "${{filt// }}" ]]; then
  ln -rs {input} {output.vcf}
else
  bcftools view {params.filt} -Oz -o {output.vcf} {input}
fi
bcftools index -t {output.vcf}
'''

def choose_vcf_general(wc):
    ds = wc['dataset']
    intype = input_type_dict[ds]
    if intype == 'vcf' and re.match(r'.+\{chrom\}', conf[ds]['infile']):
        return rules.vcf_presplit.output.vcf
    else:
        return rules.vcf_split.output.vcf

def choose_tbi_general(wc):
    return choose_vcf_general(wc) + '.tbi'

rule bcf:
    input:
        vcf = choose_vcf_general,
        tbi = choose_tbi_general,
        fasta = lambda wc: ref_fasta[wc["build"]]
    output: "intermediate/{dataset}.{build}.chr{chrom}.bcf"
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 1440
    shell:
        """
bcftools norm -Ob -o {output} -d none -f {input.fasta} {input.vcf} && \
bcftools index {output}
"""

module shapeit:
    snakefile: snakefile_shapeit
    config: {'AC': True}

use rule * from shapeit as shapeit_*

use rule convert_phased from shapeit as shapeit_convert_phased with:
    output: "intermediate/{genotypes}.hg38.chr{chrom}.shapeit5.vcf.gz"

use rule shapeit_filter from shapeit as shapeit_shapeit_filter with:
    input: "intermediate/{genotypes}.hg38.chr{chrom}.bcf"
    output: temp('temp/shapeit_filtered/{genotypes}.chr{chrom}.filtered.bcf')

rule makeref:
    input:
        vcf = lambda wc: ref_vcf[wc["build"]], 
        fasta = lambda wc: ref_fasta[wc["build"]]
    output: "reference_proc/{refname}.{build}.chr{chrom}.bcf"
    conda: "envs/bcftools.yaml"
    threads: 4
    resources:
        mem_mb = 4000,
        time_min = 60
    shell:
        '''
bcftools view -Ou -c 2 {input.vcf} | \
  bcftools norm -Ou -m -any | \
  bcftools norm -Ob -o {output} -d none -f {input.fasta} && \
 bcftools index -f {output}
'''

rule process_smap_1kg_hgdp:
    input:
        metadata = HTTP.remote("storage.googleapis.com/gcp-public-data--gnomad/release/3.1.2/vcf/genomes/gnomad.genomes.v3.1.2.hgdp_1kg_subset_sample_meta.tsv.bgz")
    output:
        table = "reference_proc/hgdp_1kg.popdata.tsv.gz",
        smap = "reference_proc/hgdp_1kg.smap"
    threads: 1
    resources:
        mem_mb = 512,
        time_min = 1
    script: 'scripts/rule_process_smap_1kg_hgdp.R'

admixstem = "gnomad.genomes.v3.1.2.hgdp_tgp.pruned"

rule ref_admixture_filterprune:
    input: "/sc/arion/projects/load/data-ark/Public_Unrestricted/gnomAD/3.1/vcfs/HGDP-1KG/gnomad.genomes.v3.1.2.hgdp_tgp.chr{chrom}.vcf.bgz"
    output: temp(f'reference_proc/{admixstem}.chr{{chrom}}.vcf.gz')
    conda: "envs/bcftools.yaml"
    threads: 4
    resources:
        mem_mb = 2048,
        time_min = 360
    shell:
        '''
bcftools filter -i 'FILTER="PASS" && INFO/AF[0] >= 0.05 && INFO/AF[0] <= 0.95 && F_MISSING < 0.05' {input} | \
  bcftools annotate -x 'INFO,^FORMAT/GT' | \
  bcftools view --types snps |
  bcftools +prune -m r2=0.1 -w 100kb -Oz -o {output}
'''

rule ref_admixture_cat:
    input: expand('reference_proc/{stem}.chr{chrom}.vcf.gz', stem=admixstem, chrom=range(1, 23))
    output: temp(f'reference_proc/{admixstem}.vcf.gz')
    threads: 1
    resources:
        mem_mb = 256,
        time_min = 5
    shell:
        '''
bcftools concat -Oz -o {output} {input}
'''

rule ref_plink:
    input: rules.ref_admixture_cat.output
    output: multiext(f'reference_proc/{admixstem}.', 'bed', 'bim', 'fam')
    params:
        out = lambda wc, output: output[0][:-4]
    conda: 'envs/plink.yaml'
    shell:
        '''
plink --vcf {input} --double-id --keep-allele-order --make-bed --out {params.out}
'''

rule admixture:
    input:
        bed = f"reference_proc/{admixstem}.bed",
        other = multiext(f"reference_proc/{admixstem}.", "bim", "fam")
    output:
        Qtemp = temp(f'{admixstem}.12.Q'),
        Ptemp = temp(f'{admixstem}.12.P'),
        Q = 'reference_proc/gnomad_1kg_hgdp.12.Q',
        P = 'reference_proc/gnomad_1kg_hgdp.12.P'
    log: 'reference_proc/gnomad_1kg_hgdp.12.log'
    threads: 40
    resources:
        mem_mb = 5120, # Very efficient memory usage. Previous run used 2936 MB
        time_min = 1440 # 24 hours. Should take <= 14 hours
    container: 'docker://befh/r_env_gwasamplefilt:5'
    shell:
        '''
admixture -s 42 --cv {input.bed} 12 -j{threads} 2>&1 | tee {log}
cp {output.Qtemp} {output.Q}
cp {output.Ptemp} {output.P}
'''

rule process_admixture:
    input:
        q = rules.admixture.output.Q,
        fam = f"reference_proc/{admixstem}.fam",
        pops = rules.process_smap_1kg_hgdp.output.table
    output:
        smap = "reference_proc/hgdp_1kg_filt.smap",
        rda = "reference_proc/hgdp_1kg.admixture.rda",
        samplist = "reference_proc/hgdp_1kg.filt.samplist"
    threads: 1
    resources:
        mem_mb = 512,
        time_min = 5
    container: 'docker://befh/r_procadmix:v1'
    script: 'scripts/rule_process_admixture.R'

rule report_refadmix:
    input: rules.process_admixture.output.rda
    output: 'reference_proc/hgdp_1kg.admixture.html'
    threads: 1
    resources:
        mem_mb = 1024,
        time_min = 10
    container: 'docker://befh/r_procadmix:v1'
    script: 'scripts/rule_report_refadmix.Rmd'

rule get_refsamp:
    input: lambda wc: ref_pops[wc["build"]]
    output: "reference_proc/{refname}.{build}.fromsmap.samplist" 
    threads: 4
    resources:
        mem_mb = 4000,
        walltime = '96:00'
    shell: r'''awk -F '\t' 'NR > 1 {{print $1}}' {input} > {output}'''

def choose_vcf_ref(wc):
    ds = wc['dataset']
    intype = input_type_dict[ds]
    if conf[ds].get('phased', False):
        assert intype == 'vcf', 'plink files cannot be phased and bcf files are not yet supported'
        return conf[ds]['infile']
    elif conf[ds].get('impute', False):
        assert input_type_dict[ds] != 'vcf', 'cannot impute vcf yet'
        return 'output/imputation/data/by_chrom/{dataset}_chr{chrom}_filtered.vcf.gz',
    elif wc['build'] == 'hg38':
        return "intermediate/{dataset}.{build}.chr{chrom}.forgnomix.vcf.gz"
    elif intype == 'vcf' and re.match(r'.+\{chrom\}', conf[ds]['infile']):
        return rules.vcf_presplit.output.vcf
    else:
        return rules.vcf.output.vcf

rule filter_ref:
    input:
      ref = rules.makeref.output,
      samp = choose_vcf_ref,
      ref_samples = lambda wc: rules.process_admixture.output.samplist if wc['build'] == "hg38" else rules.get_refsamp.output
    output: "reference_proc/{refname}.{build}.chr{chrom}.filtered_{dataset}.vcf.gz"
    conda: "envs/bcftools.yaml"
    threads: 4
    resources:
        mem_mb = 1024,
        walltime = '96:00'
    shell:
        '''
bcftools view --regions-file {input.samp} --samples-file {input.ref_samples} --force-samples -Oz -o {output} {input.ref}
bcftools index -f {output}
'''

rule eagle:
    input:
        target = rules.bcf.output,
        ref = lambda wc: expand("reference_proc/{refname}.{{build}}.chr{{chrom}}.bcf", refname=ref_name[wc['build']])
    output: "intermediate/{dataset}.{build}.chr{chrom}.eagle2.vcf.gz"
    params:
        outstem = "intermediate/{dataset}.{build}.chr{chrom}.eagle2"
    log: "logs/{dataset}_{build}_chr{chrom}.eagle.log"
    threads: 20
    resources:
        mem_mb = 4000,
        walltime = '96:00'
    container: 'docker://befh/eagle:v2.4.1'
    shell:
        '''
eagle --vcfTarget={input.target} --vcfRef={input.ref} \
  --geneticMapFile=/tables/genetic_map_{wildcards.build}_withX.txt.gz \
  --outPrefix={params.outstem} --numThreads={threads} --vcfOutFormat=z \
  2>&1 | tee {log}
'''

rule geneticMapGnomix:
    input: HTTP.remote("https://storage.googleapis.com/broad-alkesgroup-public/Eagle/downloads/tables/genetic_map_{build}_withX.txt.gz") if iconnect else ''
    output: "reference_proc/genetic_map_{build}_withX.gmap"
    resources:
        mem_mb = 1000,
        time_min = 30
    shell:
        r'''
zcat {input} | \
  awk 'BEGIN {{OFS="\t"; print "#chromosome\tposition\tGenetic_Map(cM)"}} NR > 1 {{print $1,$2,$4}}' \
  > {output}
'''

def choose_vcf_gnomix(wc):
    ds = wc['dataset']
    intype = input_type_dict[ds]
    if conf[ds].get('impute', False):
        assert input_type_dict[ds] != 'vcf', 'cannot impute vcf yet'
        return 'output/imputation/data/by_chrom/{dataset}_chr{chrom}_filtered.vcf.gz',
    elif conf[ds].get('phased', False):
        assert intype == 'vcf', 'plink files cannot be phased and bcf files are not yet supported'
        return choose_vcf_general(wc)
    elif wc['build'] == 'hg38':
        return "intermediate/{dataset}.hg38.chr{chrom}.shapeit5.vcf.gz"
    else:
        return "intermediate/{dataset}.{build}.chr{chrom}.eagle2.vcf.gz"
    
rule vcf_gnomix:
    input: choose_vcf_gnomix
    output: "intermediate/{dataset}.{build}.chr{chrom}.forgnomix.vcf.gz",
    resources:
        mem_mb = 4000,
        time_min = 240
    shell: '''
ln -rs {input} {output}
'''

rule sample_list:
    input: lambda wc: expand("intermediate/{{dataset}}.{build}.chr{chrom}.forgnomix.vcf.gz", chrom=CHROMS, build=build_dict[wc["dataset"]])
    output: "intermediate/sample_lists/{dataset}_all.txt",
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 30
    shell: "bcftools query -l {input[0]} > {output}"

checkpoint sample_list_split:
    input: ancient(rules.sample_list.output)
    output: directory("intermediate/sample_lists/split_{dataset}")
    params:
        splitstem = "intermediate/sample_lists/split_{dataset}/split."
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 30
    shell: "mkdir -p {output} && split -l 100 -a 4 -d {input} {params.splitstem}"

rule splits:
    input:
        sample_list = "intermediate/sample_lists/split_{dataset}/split.{chunk}",
        vcf = rules.vcf_gnomix.output
    output:
        vcf = temp("intermediate/{dataset}.{build}.chr{chrom}.chunk{chunk}.vcf.gz"),
        tbi = temp("intermediate/{dataset}.{build}.chr{chrom}.chunk{chunk}.vcf.gz.tbi"),
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 960
    shell:
        '''
bcftools view --samples-file {input.sample_list} -Oz -o {output.vcf} {input.vcf}
bcftools index -tf {output.vcf}
'''

rule vcf_model_fit:
    input:
        sample_list = rules.sample_list.output,
        vcf = rules.vcf_gnomix.output
    output:
        sample_list = temp("intermediate/{dataset}.{build}.chr{chrom}.modelfit.samples"),
        vcf = temp("intermediate/{dataset}.{build}.chr{chrom}.modelfit.vcf.gz"),
        tbi = temp("intermediate/{dataset}.{build}.chr{chrom}.modelfit.vcf.gz.tbi"),
    conda: "envs/bcftools.yaml"
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 960
    shell:
        '''
head -n4 {input.sample_list} > {output.sample_list}
bcftools view --samples-file {output.sample_list} -Oz -o {output.vcf} {input.vcf}
bcftools index -tf {output.vcf}
'''

#import ipdb; ipdb.set_trace()

rule download_config:
    input: HTTP.remote(f'{reporoot}/configs/{{conf}}.yaml') if iconnect else f'{reporoot}/configs/{{conf}}.yaml'
    output: 'intermediate/configs/{conf}.yaml'
    threads: 1
    resources:
        mem_mb = 4000,
        time_min = 5
    shell: 'cp {input} {output}'

rule gnomix_model:
    input:
        query = "intermediate/{dataset}.{build}.chr{chrom}.modelfit.vcf.gz",
        genetic_map = rules.geneticMapGnomix.output,
        reference = lambda wc: expand("reference_proc/{refname}.{{build}}.chr{{chrom}}.filtered_{{dataset}}.vcf.gz", refname=ref_name[wc['build']]),
        sample_map =  lambda wc: ref_pops[wc['build']],
        config = lambda wc: gconfig_local_dict[wc["dataset"]]
    output:
        'output/models/{dataset}_{build}_chr{chrom}/models/model_chm_{chrom}/model_chm_{chrom}.pkl'
    params:
        output_folder = 'output/models/{dataset}_{build}_chr{chrom}',
        phase = 'False', #True or False
    threads: 40
    resources:
        mem_mb = 8000,
        walltime = '140:00'
    container: "docker://befh/gnomix:v2"
    shell:
        '''
python3 /gnomix/gnomix.py {input.query} {params.output_folder} \
  {wildcards.chrom} {params.phase} \
  {input.genetic_map} {input.reference} {input.sample_map} \
  {input.config}
'''

gchunkdir = 'output/chunked/{dataset}_{build}_chr{chrom}_chunk{chunk}'

rule gnomix:
    input:
        query = rules.splits.output.vcf,
        tbi = rules.splits.output.tbi,
        model = rules.gnomix_model.output
    output:
        vcf = temp(gchunkdir + '/query_file_phased.vcf'),
        fb = gchunkdir + '/query_results.fb',
        msp = gchunkdir + '/query_results.msp'
    params:
        output_folder = gchunkdir,
        phase = 'True', #True or False
    threads: 40
    resources:
        mem_mb = 3000,
        walltime = '140:00'
    container: "docker://befh/gnomix:v2"
    shell:
        '''
python3 /gnomix/gnomix.py {input.query} {params.output_folder} \
  {wildcards.chrom} {params.phase} {input.model}
'''

rule Compress:
    input: gchunkdir + '/query_file_phased.vcf'
    output:
        vcf = gchunkdir + '/{dataset}_chr{chrom}.vcf.gz',
        tbi = gchunkdir + '/{dataset}_chr{chrom}.vcf.gz.tbi'
    threads: 2
    resources:
        mem_mb = 4000,
        walltime = '24:00'
    conda: "envs/bcftools.yaml"
    shell:
        '''
bcftools view -Oz -o {output.vcf} {input}
bcftools index -tf {output.vcf}
'''

gchunkdirp = 'output/chunked/{{dataset}}_{{build}}_chr{{chrom}}_chunk{chunk}'

def aggregate(wildcards, fname):
    checkpoint_output = checkpoints.sample_list_split.get(**wildcards).output[0]
    chunks = glob_wildcards(checkpoint_output + "/split.{chunk}").chunk
    # ins = {
    #     "vcf": expand(gchunkdir + '/{{dataset}}_chr{{chrom}}.vcf.gz', chunk=chunks),
    #     "fb": expand(gchunkdir + '/query_results.fb', chunk=chunks),
    #     "msp": expand(gchunkdir + '/query_results.msp', chunk=chunks)
    # }
    # return ins
    return expand(gchunkdirp + fname, chunk=chunks)

rule merge_gnomix:
    input:
        vcf = lambda wc: aggregate(wc, '/{{dataset}}_chr{{chrom}}.vcf.gz'),
        tbi = lambda wc: aggregate(wc, '/{{dataset}}_chr{{chrom}}.vcf.gz.tbi'), 
        fb = lambda wc: aggregate(wc, '/query_results.fb'), 
        msp = lambda wc: aggregate(wc, '/query_results.msp') 
    output:
        vcf = 'output/merged/{dataset}_{build}_chr{chrom}.vcf.gz',
        tbi = 'output/merged/{dataset}_{build}_chr{chrom}.vcf.gz.tbi',
        msp = 'output/merged/{dataset}_{build}_chr{chrom}.msp',
        fb = 'output/merged/{dataset}_{build}_chr{chrom}.fb',
        tmp = temp('output/merged/{dataset}_{build}_chr{chrom}.tmp')
    threads: 2
    resources:
        mem_mb = 4000,
        walltime = '24:00'
    conda: "envs/gnomad_merge.yaml"
    shell:
        r'''
bcftools merge -Oz -o {output.vcf} {input.vcf}
bcftools index -tf {output.vcf}

tmpfile={output.tmp}
out_msp={output.msp}
out_fb={output.fb}

msps=({input.msp}) # make array of inputs
msp_first="${{msps[0]}}"
cp "$msp_first" "$out_msp" # copy first input to output
msps=("${{msps[@]:1}}") # delete first input from array

for msp in ${{msps[@]}}; do
  if ! diff -q <(cut -f1-6 "$msp_first") <(cut -f1-6 "$msp"); then
    echo "$msp has different variant ranges than the first chunk"
    exit 1
  fi
  paste "$out_msp" <(cut -f1-6 --complement $msp) > "$tmpfile"
  cp "$tmpfile" "$out_msp"
  nrow=$(cat "$out_msp" | tail -n +3 | wc -l)
  ncol=$(sed -n '2{{s/\t/\n/g;p;q}}' "$out_msp" | tail -n +7 | wc -l)
  echo $msp "$nrow" rows, "$ncol" columns
done

rm "$tmpfile"

fbs=({input.fb}) # make array of inputs
fb_first="${{fbs[0]}}"
cp "$fb_first" "$out_fb" # copy first input to output
fbs=("${{fbs[@]:1}}") # delete first input from array

for fb in ${{fbs[@]}}; do
  if ! diff -q <(cut -f1-4 "$fb_first") <(cut -f1-4 "$fb"); then
    echo "$msp has different variant ranges than the first chunk"
    #exit 1
  fi
  paste $out_fb <(cut -f1-4 --complement $fb) > "$tmpfile"
  cp "$tmpfile" "$out_fb"
  nrow=$(cat "$out_fb" | tail -n +3 | wc -l)
  ncol=$(sed -n '2{{s/\t/\n/g;p;q}}' "$out_fb" | tail -n +5 | wc -l)
  echo $fb: "$nrow" rows, "$ncol" columns
done

get_head () {{
  awk 'NR == 1 {{a[$0]; print; next}} FNR == 1 && !($0 in a) \
    {{print "Header comment different"; exit 1}}' $@
}}

replace_head () {{ sed -i "1 s|^.*$|$1|" $2 ; }}

header_fb="$(get_head {input.fb})"
header_msp="$(get_head {input.msp})"

replace_head "$header_fb" "$out_fb"
replace_head "$header_msp" "$out_msp"
'''

rule Concatenate:
    input:
        vcf = expand('output/merged/{{dataset}}_{{build}}_chr{chrom}.vcf.gz', chrom=CHROMS),
        tbi = expand('output/merged/{{dataset}}_{{build}}_chr{chrom}.vcf.gz.tbi', chrom=CHROMS),
    output:
        vcf = 'output/{dataset}_{build}_chrall.vcf.gz',
        tbi = 'output/{dataset}_{build}_chrall.vcf.gz.tbi'
    threads: 4
    resources:
        mem_mb = 4000,
        walltime = '24:00'
    conda: "envs/bcftools.yaml"
    shell:
        r'''
bcftools concat -Oz -o {output.vcf} --threads 2 {input.vcf}
bcftools index -tf {output.vcf}
'''

rule Merge:
    input:
        vcf = expand('output/{dataset}_{build}_chrall.vcf.gz', zip, dataset=DATASETS, build=BUILD),
        tbi = expand('output/{dataset}_{build}_chrall.vcf.gz.tbi', zip, dataset=DATASETS, build=BUILD)
    output:
        vcf = "output/merged.vcf.gz",
        tbi = "output/merged.vcf.gz.tbi"
    threads: 4
    resources:
        mem_mb = 4000,
        walltime = '24:00'
    conda: "envs/bcftools.yaml"
    shell:
        r'''
bcftools merge -m none -Oz -o {output.vcf} --threads 2 {input.vcf}
bcftools index -tf {output.vcf}
'''
