verbose: True
seed: 94305

model: 
  n_cores:                   # number of CPUs to use, default is maximum

inference:
  bed_file_output: False
  snp_level_inference: False # output ancestry inference for each marker of the query file
  visualize_inference: False # visualize chromosome paintings, beta version
